enum tokens {STRING, ID, VERY, SO, DOGETYPE, IS,
			MORE, LESS, LOTS, FEW,
			PLZ, GOTOTHEMOON,
			RLY, NOTRLY, BUT, MANY,
			NEXT,
			NOT, AND, OR, BIGGER, SMALLER, BIGGERISH, SMALLERISH, SAME,
			};
